import = [
    "~/.cache/wal/colors-alacritty.toml"
]
[colors]
transparent_background_colors = true

[window]
opacity = 0.75

[font]
size = 11
normal = { family = "Maple Mono NF", style = "Regular" }
